schedule/grafik/urls.py
from django.contrib import admin
from django.urls import path
from .views import index, add_worker, two

app_name = 'grafik'

urlpatterns = [
    path('', index, name='index'),
    path('addworker', add_worker, name='add_worker'),
    path('asdas', two),
]

schedule/schedule/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('app/', include('grafik.urls')),
]

schedule/grafik/models.py
from django.db import models

# Create your models here.

schedule/grafik/views.py
from django.http import HttpResponse
from django.shortcuts import render
from django import forms

from collections import defaultdict

workers = ['Harry', 'Ron']
vacations = {'Harry': 1, 'Ron': 2}
vacations = defaultdict(list)


class AddNewWorker(forms.Form):
    name = forms.CharField(label='New worker')
    filterOption = forms.ChoiceField(widget=forms.RadioSelect, choices=list(enumerate(workers)))


class ChoiseWorker(forms.Form):
    worker = forms.ChoiceField(choices=tuple(enumerate(workers)))
    vacation_start = forms.IntegerField()
    vacation_finish = forms.IntegerField()


def index(request):
    return render(request, 'index.html', context={'workers': workers})


def add_worker(request):
    if request.method == 'POST':
        form = AddNewWorker(request.POST)
        if form.is_valid():
            worker = form.cleaned_data['name']
            workers.append(worker)
        elif ChoiseWorker(request.POST).is_valid():
            print('SSSSSSSSS')
            form = ChoiseWorker(request.POST)
            vacations[workers[int(form.data['worker'])]] += list(
                range(int(form.data['vacation_start']), int(form.data['vacation_finish']) + 1))
            print(vacations)
        else:
            print('ERROROROROOROR')
            return render(request, 'index.html')

    return render(request, 'add_worker.html', context={'form': AddNewWorker(),
                                                       'form2': ChoiseWorker(),
                                                       'workers': workers})


def two(request):
    return HttpResponse('asdasdas')

schedule/grafik/templates/add_worker.html
{% extends 'base.html' %}


<h1>add worker</h1>
{% block body %}
    <form action="{% url 'grafik:add_worker' %}" method="post">
        {% csrf_token %}
        {{ form }}
        <input type="submit">
    </form>
    <h1>List workers:</h1>

    {% for worker in workers %}

        <li>{{worker}}</li>

    {% endfor %}
    <form action="" method="post">
        {% csrf_token %}
        {{ form2 }}
        <input type="submit">
    </form>
{% endblock %}

schedule/grafik/templates/base.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Title</title>
</head>
<body>
{% block body %}
{% endblock %}
</body>
</html>

schedule/grafik/templates/index.html
{% extends 'base.html' %}

{% block body %}

    <h1>List workers:</h1>

    {% for worker in workers %}

        <li>{{worker}}</li>

    {% endfor %}


{% endblock %}